services:
  optimy-app:
    build: src/php/
    container_name: optimy-app-container
    env_file: ".env"
    depends_on:
      - optimy-db
    ports:
      - "8080:80"

  optimy-db:
    build: src/mysql/
    container_name: optimy-db-container
    env_file: ".env"
    ports:
      - "3306:3306"
