services:
  optimy-app:
    build: .
    container_name: optimy-app-container
    env_file: ".env"
    volumes:
      - ./src/php:/var/www/html
    depends_on:
      - optimy-db
    ports:
      - "8080:80"

  optimy-db:
    image: mysql:9.0.0
    container_name: optimy-db-container
    env_file: ".env"
    ports:
      - "3306:3306"
    volumes:
      - ./src/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
