AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Docker containers from ECR to EC2

Parameters:
  dbpass:
    Type: String
    Default: rootpassword
  dbname:
    Type: String
    Default: testdb
  dbhost:
    Type: String
    Default: optimy-db
  dbuser:
    Type: String
    Default: root

Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties: 
      InstanceType: t2.medium
      KeyName: private  # Replace with your key pair name
      ImageId: ami-06c68f701d8090592
      IamInstanceProfile: 
        Ref: EC2InstanceProfile
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install docker -y
          systemctl --now enable docker
          systemctl restart docker
          usermod -aG docker ec2-user
          yum install -y aws-cli
          aws ecr get-login-password --region ${AWS::Region} | docker login --username AWS --password-stdin ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          docker pull ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/optimy-db:latest
          docker pull ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/optimy-app:latest
          docker pull ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/optimy-testing:latest
          docker network create optimynetwork
          docker run -d --name optimy-db --network optimynetwork -p 3306:3306 -e MYSQL_ROOT_PASSWORD=${dbpass} -e MYSQL_DATABASE=${dbname} ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/optimy-db:latest
          docker run -d --name optimy-app --network optimynetwork -p 8080:80 -e DB_HOST=${dbhost} -e DB_USER=${dbuser} -e DB_PASS=${dbpass} -e DB_NAME=${dbname} ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/optimy-app:latest
          sleep 30
          docker run -d --name optimy-testing --network optimynetwork -p 8089:8089 -e BASE_URL=http://optimy-app:8080 ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/optimy-testing:latest
      NetworkInterfaces: 
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          SubnetId: subnet-05b48d2b722dcdc90  # Replace with your subnet ID
          GroupSet: 
            - Ref: MySecurityGroup

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: Allow SSH and HTTP
      VpcId: vpc-0f905afcd9ffedc5d # Replace with your VPC ID
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0

  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties: 
      Roles: 
        - Ref: EC2InstanceRole

  EC2InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement: 
          - Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      Policies: 
        - PolicyName: ECRAccessPolicy
          PolicyDocument: 
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: 
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:GetAuthorizationToken
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: The Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
